 enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "both"
version = "latest"
excluded-patches = "'Custom branding' 'Theme' 'Enable debugging' 'GmsCore support'"
patcher-args = "-e 'Custom branding' -OcustomName=revanced music"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "both"
version = "latest"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
version = "latest"
excluded-patches = "'Remove viewer discretion dialog' 'Disable double tap actions' 'Downloads' 'Custom branding' 'Change header' 'Wide search bar' 'Shorts autoplay' 'C>
